name: Python application

on:
#  push:
  schedule:
    - cron: '30 5 * * 1-5'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Script
      env:
        GSHEETS_CREDS_JSON: ${{ secrets.GSHEETS_CREDS_JSON }}
        CSV_SEP_METHOD_GSHEET: ${{ secrets.CSV_SEP_METHOD_GSHEET }}
      run: python csv_to_gsheets.py
