name: Python application

on:
  push:
  schedule:
    - cron: '30 5 * * 0-6'
  
jobs:
  driver_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Script
      env:
        LINK_LOGIN: ${{ secrets.LINK_LOGIN }}
        COOKIE_URL: ${{ secrets.COOKIE_URL }}
        PWD: ${{ secrets.PWD }}
        LINK_MESSAGE: ${{ secrets.LINK_MESSAGE }}
      run: python driver.py
